name: face_recongantion
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"



dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  firebase_storage: ^10.2.17
  firebase_messaging: ^11.4.1
  smooth_page_indicator: ^1.0.0+2
  camera: ^0.9.6
  path_provider: ^2.0.11
  path:
  permission_handler: ^9.2.0
  video_player: ^2.4.4
  camera_web:
  image_picker: ^0.8.5+3
  pin_code_fields: ^7.4.0
  flutter_verification_code: ^1.1.3
  custom_timer: ^0.1.1
  google_maps_flutter: ^2.1.8
  geolocator: ^5.3.1
  provider: ^6.0.3
  modal_progress_hud_nsn: ^0.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^1.0.0



flutter:


  uses-material-design: true

  assets:
    - assets/images/



  fonts:
    - family: Kaushan Script
      fonts:
        - asset: assets/fonts/KaushanScript-Regular.ttf

